openapi: 3.0.3
info:
  title: Task Manager API
  description: API for managing agent task status and history
  version: 1.0.0
  contact:
    name: Task Manager Team
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/health:
    get:
      summary: Health check
      description: Check if the Task Manager service is healthy
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                    example: "1.0.0"

  /api/tasks/{identifier}/status:
    put:
      summary: Update task status
      description: Update task status and create history record for a task
      operationId: updateTaskStatus
      parameters:
        - name: identifier
          in: path
          required: true
          description: Task identifier (session_id or task_id)
          schema:
            type: string
            example: "session_123"
        - name: id_type
          in: query
          required: false
          description: Type of identifier (defaults to session_id)
          schema:
            type: string
            enum: [session_id, task_id]
            default: session_id
            example: "session_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Task status updated successfully"
                  task_id:
                    type: string
                    example: "task_456"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{identifier}:
    get:
      summary: Get current task status
      description: Get the current status of a task by identifier
      operationId: getTaskStatus
      parameters:
        - name: identifier
          in: path
          required: true
          description: Task identifier (session_id or task_id)
          schema:
            type: string
            example: "session_123"
        - name: id_type
          in: query
          required: false
          description: Type of identifier (defaults to session_id)
          schema:
            type: string
            enum: [session_id, task_id]
            default: session_id
            example: "session_id"
      responses:
        '200':
          description: Task status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/TaskStatus'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{identifier}/history:
    get:
      summary: Get task history
      description: Get complete task history including status changes and logs
      operationId: getTaskHistory
      parameters:
        - name: identifier
          in: path
          required: true
          description: Task identifier (session_id or task_id)
          schema:
            type: string
            example: "session_123"
        - name: id_type
          in: query
          required: false
          description: Type of identifier (defaults to session_id)
          schema:
            type: string
            enum: [session_id, task_id]
            default: session_id
            example: "session_id"
      responses:
        '200':
          description: Task history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/TaskHistory'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    TaskUpdate:
      type: object
      required:
        - session_id
        - jira_ticket
        - status
        - current_action
        - message
      properties:
        session_id:
          type: string
          description: Session unique identifier
          example: "session_123"
        jira_ticket:
          type: string
          description: Jira ticket number
          example: "PROJ-789"
        status:
          type: string
          enum: [running, success, failed]
          description: Task status
          example: "running"
        current_action:
          type: string
          description: Current action description
          example: "Processing user request"
        progress_percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Progress percentage (0-100)
          example: 25.0
        message:
          type: string
          description: Status description message
          example: "Started analyzing codebase"
        details:
          type: object
          description: Additional task details
          additionalProperties: true
          example:
            file_count: 15
            complexity: "medium"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the update
          example: "2024-12-30T10:30:00Z"

    TaskStatus:
      type: object
      properties:
        task_id:
          type: string
          description: Task unique identifier (generated by Task Manager)
          example: "task_456"
        session_id:
          type: string
          description: Session unique identifier
          example: "session_123"
        jira_ticket:
          type: string
          description: Jira ticket number
          example: "PROJ-789"
        status:
          type: string
          enum: [running, success, failed]
          description: Current task status
          example: "running"
        current_action:
          type: string
          description: Current action description
          example: "Processing user request"
        progress_percentage:
          type: number
          format: float
          description: Progress percentage (0-100)
          example: 25.0
        message:
          type: string
          description: Status description message
          example: "Started analyzing codebase"
        details:
          type: object
          description: Additional task details
          additionalProperties: true
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
          example: "2024-12-30T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2024-12-30T10:30:00Z"

    TaskHistory:
      type: object
      properties:
        task_info:
          $ref: '#/components/schemas/TaskStatus'
        status_history:
          type: array
          description: List of status changes
          items:
            type: object
            properties:
              id:
                type: integer
                description: History record ID
                example: 1
              status:
                type: string
                enum: [running, success, failed]
                description: Status at this point
                example: "running"
              current_action:
                type: string
                description: Action at this point
                example: "Started task"
              progress_percentage:
                type: number
                format: float
                description: Progress at this point
                example: 0.0
              message:
                type: string
                description: Message at this point
                example: "Task initialized"
              details:
                type: object
                description: Additional details at this point
                additionalProperties: true
              created_at:
                type: string
                format: date-time
                description: Timestamp of this status change
                example: "2024-12-30T10:00:00Z"
        logs:
          type: array
          description: List of log entries
          items:
            type: object
            properties:
              id:
                type: integer
                description: Log entry ID
                example: 1
              log_level:
                type: string
                enum: [DEBUG, INFO, WARN, ERROR]
                description: Log level
                example: "INFO"
              log_message:
                type: string
                description: Log message
                example: "Task started successfully"
              created_at:
                type: string
                format: date-time
                description: Log entry timestamp
                example: "2024-12-30T10:00:00Z"

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message
          example: "Session not found"
        code:
          type: string
          description: Error code
          example: "SESSION_NOT_FOUND"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2024-12-30T10:30:00Z"

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []